backend:
  name: github
  repo: "Astroblazter/Domik-v-kolomne3"
  branch: "cloudflare-cms-test"
  base_url: "https://domik-oauth-proxy.orlovdove.workers.dev"

media_folder: "public/images"
public_folder: "/images"

locale: ru

collections:
  - name: "news"
    label: "Новости"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }
